config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'messages#index'
  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :context, presence: true, length: {maximum: 30}
  validates :title, presence: true, length: {maximum: 20}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  def index
    @pagy, @messages = pagy(Message.order(id: :desc), items: 10)
  end

  def show
  end

  def new
    @message = Message.new()
  end

  def create
    @message = Message.new(message_params)
    
    if @message.save
      flash[:success] = '保存成功'
      redirect_to messages_path
    else
      flash[:danger] = '保存失敗'
      render :new
    end
  end

  def edit
  end

  def update
    if @message.update(message_params)
      flash[:success] = '編集成功'
      redirect_to @message
    else
      flash[:danger] = '編集失敗'
      render :edit
    end
  end

  def destroy
    @message.destroy
    flash[:success] = '削除成功'
    redirect_to messages_url
  end

  private

  def message_params
    params.require(:message).permit(:title, :context)
  end

  def set_message
    @message = Message.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/layouts/_flash_message.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %> text-center">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Messageboard</a>
      <%= link_to '新規作成', new_message_path, class: 'd-flex btn btn-primary'%>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Msgboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" 
          rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" 
          crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_message'%>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" 
            integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" 
            crossorigin="anonymous"></script>
  </body>
</html>

app/views/messages/_error_message.html.erb
<% if message.errors.any? %>
  <div id="error_explanation" class="text-danger alert alert-danger">
    <h2>
      <%= pluralize(message.errors.count, 'error') %>prohibited this message from being saved:
    </h2>

    <ul>
      <% message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/messages/_form_message.html.erb
<%= form_with model: message do |f| %>
  <%= render 'messages/error_message', message: message %>

  <div class="row">
    <%= f.label :title, 'タイトル', class: 'col-sm-1' %>
    <%= f.text_field :title, class: 'w-25' %>
  </div>

  <div class="row">
    <%= f.label :context, 'メッセージ', class: 'col-sm-1' %>
    <%= f.text_field :context, class: 'w-25' %>
  </div>

  <%= f.submit '保存', class: 'btn btn-primary rounded' %>
<% end %>

app/views/messages/edit.html.erb
<h1>編集 : <%= @message.id %></h1>

<%= render 'messages/form_message', message: @message %>

<%= link_to '詳細へ', message_path(@message), class: 'btn btn-secondary' %> 
<%= link_to '一覧へ', root_path, class: 'btn btn-secondary' %>

app/views/messages/index.html.erb
<h1>メッセージ一覧</h1>

<% if @messages.any? %>
  <table class="table table-striped table-bordered"> 
      <tr style="background-color: #aaa">
        <th>id</th>
        <th>タイトル</th>
        <th>メッセージ</th>
      </tr>
      <% @messages.each do |msg| %>
        <tr>
          <td><%= link_to msg.id, message_path(msg) %></td>
          <td><%= msg.title %></td>
          <td><%= msg.context %></td>
        </tr>
      <% end %>

    <%== pagy_nav(@pagy) %>
  </table>
<% else %>
  <h3 class="d-flex justify-content-center text-danger">メッセージ未登録</h3>
<% end %>

<%= link_to '新規作成', new_message_path %>

app/views/messages/new.html.erb
<h1>新規作成</h1>

<%= render 'messages/form_message', message: @message %>

<%= link_to '一覧へ', root_path %>

app/views/messages/show.html.erb
<h1>メッセージ詳細 : <%= @message.id %></h1>

<h5><%= @message.title %></h5>
<p><%= @message.context %></p>

<%= link_to '編集へ', edit_message_path(@message), class: 'btn btn-secondary' %> 
<%= link_to '一覧へ', root_path, class: 'btn btn-secondary' %> 
<%= link_to '削除', message_path(@message), method: :delete, data: {confirm: 'よろしいですか？'},
    class: 'btn btn-danger' %>